apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newapplication
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/arastusharma/nginx-config.git
    targetRevision: HEAD
    path: Nginx
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapplication

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
